write_endpoint: azure_ai_search

endpoints:

#Azure endpoints
  azure_ai_search:
    enabled: true
    api_key_env: AZURE_AI_SEARCH_API_KEY
    api_endpoint_env: AZURE_AI_SEARCH_ENDPOINT
    index_name: embeddings1536
    db_type: azure_ai_search
